### ISSUE TITLE
[Story] Calendar legends modification

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1034]
## 🌈 Objective

As a User host\
I want to be able to see different legends for rental and activity
So that I'll be able to quickly distinguish between rental bookings and activity reservations on the calendar.

### Requirements
1. Activity legends will be
- Confirmed
- Arrived
-Completed
-etc.

2. Rental Legends
- Confirmed
- Picked-up
- Drop off

### Design Workflow
![image](https://github.com/user-attachments/assets/20a4d722-4d21-454c-a8ca-7e050d4c2a80)

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/1034-story-calendar-legends-modification
PR: https://github.com/explore-siargao/es-main/pull/1086
