### ISSUE TITLE
[FE] Change No description to Please add description in unit photo and chage tags example

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1048]
## 🌈 Objective

As a User host\
I want to be able to understand which fields are needed or required in the unit photos setup
so that I'll be able to provide all necessary information and ensure the photos are uploaded correctly without missing any important details.

### Requirements
1. Change the "No description" label to "Please add description"
2. And make the tags example and description example matched to bookable category.

### Design Workflow
![image](https://github.com/user-attachments/assets/d69f3e81-6fef-43c2-ae43-faecde836dd5)
![image](https://github.com/user-attachments/assets/f9fb2ef5-ebf2-460f-af89-98648df43f4c)

## 🗒️ Other notes
1. Apply this to all bookable category

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1067
Branch: https://github.com/explore-siargao/es-main/tree/1048-fe-change-no-description-to-please-add-description-in-unit-photo-and-chage-tags-example
