### ISSUE TITLE
[FE] Add proper example place holder in each input

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1049]
## 🌈 Objective

As a User host\

I want to be able to see an example of what to input in each field on the setup pages for all categories
so that I'll be able to accurately fill out the forms with the correct information and avoid errors during the setup process.

### Requirements
1. Add place holders in every inputs on all listing setup pages.
2. Each placeholder should provide an example of the required item to enter for that specific input.

### Design Workflow
![image](https://github.com/user-attachments/assets/9db867e4-f526-4158-9dc4-9b7b091e8a77)

## 🗒️ Other notes
1. Apply this to all bookable category

**Comment by Dyayy026** [comment]
Please check if the descriptions used are correct.

https://github.com/user-attachments/assets/51ee2ef5-0d04-4bd3-8b4d-f9554e939e96


https://github.com/user-attachments/assets/bf79ea6b-e446-4b24-b187-8bceb9ea5f3d


https://github.com/user-attachments/assets/490b1ade-b2e4-4721-bbaa-52199d537d9d

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1064
Branch: https://github.com/explore-siargao/es-main/tree/1049-story-add-proper-example-place-holder-in-each-input
