### ISSUE TITLE
[FE] Apply Calendar current day and search date function logic to motorcycle and bike 

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1090]
## 🌈 Objective
As a user host\
I want to be able see same logic of calendar filter dates and current day logic in all rentals category" 
So that you'll be able to maintain a consistent experience across all rental categories, ensuring that date filtering and the current day logic work uniformly, regardless of the type of rental (bike, car, motorcycle.). 

### Requirements
1. Apply same logic of current day and filter dates on motorbikes and bicycle calendar table.

### Design Workflow
[1qa.webm](https://github.com/user-attachments/assets/57382c03-24f2-48d3-bff1-cfb887dd56ea)

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1093
Branch: https://github.com/explore-siargao/es-main/tree/1090-fe-apply-calendar-current-day-and-search-date-function-logic-to-motorcycle-and-bike
