### ISSUE TITLE
[FE] Remove the whole place modal in the process

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1091]
## 🌈 Objective
As a user host\
I dont' want to be able see whole place modal when setting up whole place unit in listing process" 
So that you'll be able to focus only on the specific unit setup process without being distracted by the "whole place" modal, streamlining the listing process and reducing unnecessary steps when you're configuring individual units.

### Requirements
1. Remove whole place modal
2. get the whole place type on whole place type from databse.
3. If issue founded during setting up whole place fix it.

### Design Workflow
![image](https://github.com/user-attachments/assets/d05bba29-6416-40f0-b86d-6c377e8385c3)

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/1091-fe-remove-the-whole-place-modal-in-the-process
PR: https://github.com/explore-siargao/es-main/pull/1097
