### ISSUE TITLE
[FE] Create Calendar search modal 

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1099]
## 🌈 Objective
As a user host\
I want to be able to see search modal when clicking search button on all calendar reservation categories 
So that you'll be able to quickly filter and search for reservations across all calendar categories without leaving the current page, improving user experience and navigation.

### Requirements
1. Create modal that will use for searching items of reservations on calendar.

### Design Workflow
![image](https://github.com/user-attachments/assets/ff3a36a0-4297-401d-9074-ece59e45745d)

Modal will look like this
![image](https://github.com/user-attachments/assets/969701a2-253b-405f-9e98-83f7bae62565)

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/1099-fe-create-calendar-search-modal
PR: https://github.com/explore-siargao/es-main/pull/1102
