### ISSUE TITLE
[FE] Edit price per days modal

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1100]
## 🌈 Objective
As a user host\
I want to be able to see Edit price modal per dates when c;licking item headers price column 
So that you'll be able to easily adjust and update the price for specific dates directly from the calendar, ensuring quick modifications without navigating to a separate page.

### Requirements
1. Create modal for modifying price per days
2. Modal will show after clicking item header column cell
3. Modal require to enter price, from date and to date.

### Design Workflow
![image](https://github.com/user-attachments/assets/71a82c9e-4894-4609-ac94-200a4a1d96f4)

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1115
Branch: https://github.com/explore-siargao/es-main/tree/1100-fe-edit-price-per-days-modal
