### ISSUE TITLE
[FE] Add more height for image box in public listing page

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1103]
## 🌈 Objective

As a user guest\
I want to be able to see image box more bigger height 
So that I'll be able to view images in greater detail, enhancing my experience by allowing for a clearer and more immersive visual representation of the content.

### Requirements
1. Adjust the heights of image box in public page and guide pages.

### Design Workflow
![image](https://github.com/user-attachments/assets/8fa277f4-efdf-4ab0-9684-cdfd395b6c80)

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1119
Branch: https://github.com/explore-siargao/es-main/tree/1103-fe-add-more-height-for-image-box-in-public-listing-page
