### ISSUE TITLE
[FE] No bookable units calendar UI

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1120]
## 🌈 Objective

As a User host\
I don't want to see the calendar if there are no units on my listings 
so that I'll be able to avoid clutter, improve the user experience, and only display relevant data when there are units available to manage.

### Requirements
1. Show "Property units have not been created yet. Please create a property unit to display on the calendar." On property calendar.
2. Show "Rental units have not been created yet. Please create a rental unit to display on the calendar." On rental calendar.
3. Show "Activity have not been created yet. Please create a activity to display on the calendar." On activity calendar.
4. Make sure that the following will be displayed if theres no units on your listings yet.

### Design Workflow
![image](https://github.com/user-attachments/assets/359227c6-3a53-4c54-97fa-606c27de7f92)
![image](https://github.com/user-attachments/assets/58300846-a071-4ecf-b590-b3539c9d2b64)
Same on activity

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1129
Branch: https://github.com/explore-siargao/es-main/tree/1120-fe-no-bookable-units-calendar-ui
