### ISSUE TITLE
[FE] Modify Activity Setup Basic Info UI

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1123]
## 🌈 Objective

As a Guest\
I want to be able to select multiple activity types for every single activity so that I'll be able to classify activities more flexibly, cater to diverse categories, and offer a more tailored experience for users.

### Requirements
1. On Activity basic info setup add Experience type section
2. The input on Experience type will be radio button(Private and Shared)
3. Change the input of Activity type to Check boxes
4. The Items on activity type will be the following
- Island hopping
- Land tour
- Surfing lessons
- Wakeboarding
- Kite surfing
- Scuba diving
- Freediving
- Fishing
- ATV tour
5. Connect it to backend and make sure it will save after clicking save button

### Design Workflow
![Screenshot 2024-09-23 105454](https://github.com/user-attachments/assets/463d7b1d-b4ab-402b-8e1f-a31374a95767)

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1138
Branch: https://github.com/explore-siargao/es-main/tree/1123-fe-modify-activity-setup-basic-info-ui
