### ISSUE TITLE
[FE] Modify Rental and Unit Basic Info add Input number How many days before checkin can cancel 

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1140]
## 🌈 Objective

As a User host\
I want to be able to add the number of days that the property unit and rental reservation can cancel 
so that I'll be able to automatically calculate the last possible cancellation date based on the start date of the reservation.

### Requirements
1. Add input field names number of days allowed to cancel before checked-in on unit page
2. Add input field names number of days allowed to cancel before arrived on rental basic info
3. Connect the payload to backend

### Design Workflow
Unit
![image](https://github.com/user-attachments/assets/4aa296f6-8817-4cc9-8725-555cef6c2aa1)

Rental
![image](https://github.com/user-attachments/assets/498cb806-ae08-4ded-a126-b3e8c619e739)

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1149
Branch: https://github.com/explore-siargao/es-main/tree/1140-fe-modify-rental-and-unit-basic-info-add-input-number-how-many-days-before-checkin-can-cancel
