### ISSUE TITLE
[FE] Reservation Cancellation modal for all calendar types

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1148]
## 🌈 Objective

As a User host\
I want to be able to see a confirmation modal before canceling a specific reservation in all calendar reservation types so that I'll be able to prevent accidental cancellations and ensure that users are aware of the action they are taking.

### Requirements
1. Create a modal that will ask the user host if he/she is surely want to cancel the reservation
2. Apply the modal in all calendar reservation types.

### Design Workflow
![image](https://github.com/user-attachments/assets/bf989fb3-b4ad-4497-8e90-18ec02fa95ab)

## 🗒️ Other notes
1. Change the "Request to cancel" text to "Cancel Reservation"

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1159
Branch: https://github.com/explore-siargao/es-main/tree/1148-fe-reservation-cancellation-modal-for-all-calendar-types
