### ISSUE TITLE
[Bug] Bed unit not displaying correct name in listing process

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1225]
## 🌈 Objective

As a User host\
I want to be able to see correct bed unit name in all process of creating unit\
So that I'll be able to ensure accuracy and avoid confusion when managing and assigning bed units throughout the process.

### Requirements
1. Fix error on not displaying of bed name in units list
2. Fix error on not displaying name of bed in pricing setup

### Design Workflow
![image](https://github.com/user-attachments/assets/9f3408b3-9841-44ab-af12-6f1afab1c3b6)
![image](https://github.com/user-attachments/assets/2768b2fd-6966-44ba-8e3d-1a695d07c098)

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1236
Branch: https://github.com/explore-siargao/es-main/tree/1225-bug-bed-unit-not-displaying-correct-name-in-listing-process

**Comment by ramil25** [comment]
There was a problem on property pricing display on bed type in first load the data shows is right but after clicking item its undefined
