### ISSUE TITLE
[Bug] Bed unit not showing on units section in summary

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#1226]
## 🌈 Objective

As a User host\
I want to be able to see all units I added in summary step\
So that I'll be able to review and confirm all the units I’ve added before finalizing the process, ensuring everything is correct and complete.

### Requirements
1. Fix bugs where the in summary units section is not showing all bed types units.
2. On units summary also showing undefined value.

### Design Workflow
![image](https://github.com/user-attachments/assets/d30b607a-99c5-4107-99cc-827aad76b8e5)

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1227
Branch: https://github.com/explore-siargao/es-main/tree/1226-bug-bed-unit-not-showing-on-units-section-in-summary
