### ISSUE TITLE
[Feature] Remaining Rental endpoints for REST-API V2

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#2]
**Tasks List**
- [x] #7 
- [x] #8 
- [x] #9
- [x] #10
- [x] #17
- [x] #18
- [x] #19
- [x] #20
- [x] #21
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #42

**Comment by jpmadrigal07** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/2-feature-remaining-rental-endpoints-for-rest-api-v2
