### ISSUE TITLE
[Story] Implement update facilities endpoint api v2 to frontend

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#366]

**Comment by ramil25** [comment]
Branch: 
PR: https://github.com/explore-siargao/es-main/pull/367

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/366-story-implement-update-facilities-endpoint-api-v2-to-frontend
PR: https://github.com/explore-siargao/es-main/pull/372
