### ISSUE TITLE
[Story] Add Example Rental photos description and tags.

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#463]
# Requirements
1. Add example for description and tag (what are they and why should they add them?)
2. Make adding a description for each photo mandatory
3. If there is no description yet put “click photo to add description” instead of “no description” below the photos

![Screenshot 2024-07-03 160946](https://github.com/explore-siargao/es-main/assets/29083384/a891a664-bcfb-4d38-82fb-b04ef44937ec)

![Screenshot 2024-07-03 161621](https://github.com/explore-siargao/es-main/assets/29083384/a527c35b-d4d6-43ff-b9eb-da80ee68078b)

# Acceptance Criteria
All needed modification met the requiremnets.

**Comment by alkejah** [comment]
**_NOT DONE_**: 1. Add example for description and tag (what are they and why should they add them?
