### ISSUE TITLE
[Story] Remove Rental details minimum age and put driver license required

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#464]
# Requirements
1. Adjust the rentals model schema remove minimumAge column and add haveDriverLicense.
2. Adjust add and update rentaldetails function
3. Remove “minimum age” and put “drivers license required? YES/NO”. If someone has a license then they are of legal age

![Screenshot3](https://github.com/explore-siargao/es-main/assets/29083384/51af474a-e08b-4c38-90f3-b277ff9da96d)

# Acceptance Criteria
1. Make sure that the backend also adjusted base from input in frontend
2. Make sure to remove the inputs minimum age and replace it to Driver license required? with yes or no radio button

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/464-story-remove-rental-details-minimum-age-and-put-driver-license-required
PR: https://github.com/explore-siargao/es-main/pull/491
