### ISSUE TITLE
[Story] Rental Addons in others enter new fields

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#465]
# Requirements
For “Add Ons – other, please specify” I should be able to enter new fields one by one e.g Raincoat (click a button to add) Goggles (click a button to add)
![Screenshot4](https://github.com/explore-siargao/es-main/assets/29083384/79109e09-5333-4279-b789-6ff57403efad)

# Acceptance Criteria
Make sure that the Other inputs is dynamic input that can add other add-ons one by one

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/465-story-rental-addons-in-others-enter-new-fields
