### ISSUE TITLE
[Story] Rental Location Correct typo in description and put explain in detail how to get there

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#466]
# Requirements
1. ⁠In location there is a typo in the description for “how to get there”. Please put “Explain in detail how to get to your location. This will help your customers find you!”. Make this minimum 100 characters.
2. Update description below the map and put in bold “Please drag and drop the yellow marker above to set your exact location on the map”. Make this mandatory.

# Acceptance Criteria
Make sure that the typo in description is corrected and the behaviour of map is user friendly

**Comment by Dyayy026** [comment]
Work in progress:
1. Will implement modal in marker, it should have a confirmation after dragging to desired location.

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/466-story-rental-location-correct-typo-in-description-and-put-explain-in-detail-how-to-get-there
PR: https://github.com/explore-siargao/es-main/pull/519
