### ISSUE TITLE
[Story] Earnings make 3 graphs and if all selected will see full breakdown

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#467]
# Requirements
1. Payment history should actually all be under “earnings”. There will be 3 graphs (earnings, upcoming and payout history)
2. ⁠For the graph, if “all” is selected then you should be able to see a full breakdown of all of the payments from Jan-Dec not just once large bar
3. See all charts below for each filter and sections
- For this month
![Image](https://github.com/user-attachments/assets/95a6ae5a-bbb5-4cb1-97d5-74b857c30f4f)

- Filter Specefic Year
![Image](https://github.com/user-attachments/assets/ca3341a2-78e5-4756-9f0e-5165fef763c9)

- Filter specefic Month Year
![Image](https://github.com/user-attachments/assets/c2a9f6a8-6a61-4653-93f9-aa4454432ab6)

Graph other options
![Image](https://github.com/user-attachments/assets/d57984d3-a76f-4b63-ad99-7ef88836af5b)

# Acceptance Criteria
Make sure all requirements needed is followed.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/467-story-earnings-make-3-graphs-and-if-all-selected-will-see-full-breakdown
PR: https://github.com/explore-siargao/es-main/pull/790
