### ISSUE TITLE
[Story] Modified Activities schema

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#498]
# Requirements
1. Add Price object in activies schema with the following fields
- basePrice - number
-  exceedingPerPersonPrice - number
2. Add array of object name slots with the following fields
- time - string
- minimumGuestCount - number
# Acceptance Criteria
Make sure that the price in activities schema is single object and the slots is array of objects that the fields is same on requiremnet section.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/498-story-modified-activities-schema
PR: https://github.com/explore-siargao/es-main/pull/502
