### ISSUE TITLE
[Story] Include adding of slots and price in add blank activity endpoint

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#500]
# Requirements
1. Make sure that on add blank activity current endpoint include the adding of blank price and slots .
2. On price it will be 
price:{
basePrice:0,
exceedingPersonPrice:0
}
3. On slots it will be blank array
# Acceptance Criteria
Make sure to test this in Thunder or Postman and test also in frontend to see if all requirements met.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/500-story-include-adding-of-slots-and-price-in-add-blank-activity-endpoint
