### ISSUE TITLE
[Story] Include slots and price in get activity by id endpoint

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#501]
# Requirements
1. When retrieving an activity by its ID, make sure that the price and slots are included in the output.
2. Check all endpoints to ensure they still work in activities.
3. If any endpoints are affected and you encounter a problem, fix the error immediately. 

# Acceptance Criteria
1. Retrieving Activity by ID including the price and slots
2. All existing endpoints related to activities must be tested to ensure they function correctly.
3. All identified issues must be resolved promptly to restore full functionality.
4. Testing of updates should be conducted using Thunder Client or Postman to verify the changes.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/501-story-include-slots-and-price-in-get-activity-by-id-endpoint
