### ISSUE TITLE
[Story] Create custom hook for update activity pricing and slots

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#506]
# Requirements
1. Create custom hooks  name it useUpdateActivityPricingSlots
2. Save it in /web/module/Hosting/Listings/Activity/hooks folder
3. Connect the backend of update activity price and slots in hooks
4. After finishing it test the hook to check if its work.

# Acceptance Criteria
Make sure that the newly created custom hook will do the job to update the specific activity price and slots.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/506-story-create-custom-hook-for-update-activity-pricing-and-slots
