### ISSUE TITLE
[Story] Modify bookableUnitType Schema

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#509]
# Requirements
1. Add an array of objects called bedRooms to the bookableUnitTypes schema.
2. The shape of each bedRoom object will be like this:
```
{
bedRoomName:string,
bedRoomType:string
}
```
3. bedRooms is nullable
# Acceptance Criteria
Follow all requirements above.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/509-story-modify-bookableunittype-schema
