### ISSUE TITLE
[Story] Modify add and update whole place endpoint

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#510]
# Requirements
1. In the "Add Blank Whole Place" section, make sure that the bedRooms value is an empty array [].
2. In the "Add Blank Room and Beds" section, make sure that the bedRooms value is null.
3. Modify the "Update Whole Place" endpoint to ensure that bedRooms is included in req.body.
4. Test all modified endpoints using Thunder or Postman.

# Acceptance Criteria
1. Follow all the requirements above.
2. Make sure all modified endpoints are tested.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/510-story-modify-add-and-update-whole-place-endpoint
