### ISSUE TITLE
[Story] Connect whole place beds payloads frontend to backend

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#511]
# Requirements
1. Make sure that the bedRooms payload is included in the updateWholeplace hooks in the frontend.
2. Make sure that after saving the whole place's basic info, when you go back, all added bedrooms are there.
![image](https://github.com/explore-siargao/es-main/assets/29083384/ac3ae8cf-89cd-4467-bc41-8563387cc126)
3. Change the Whole place name input from dropdown select to input text.
4. Test all changes to verify if they are working properly.
# Acceptance Criteria.
1. Follow all the requirements above.
2. Make sure all processes in the frontend are working properly.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/511-story-connect-whole-place-beds-payloads-frontend-to-backend
