### ISSUE TITLE
[Feature] Connect public listing property single view to backend

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#520]
# Requirements
1. Connect `/listing/property/:id` page to backend api endpoint of getPropertyById
![Image](https://github.com/explore-siargao/es-main/assets/29083384/d8638144-4000-46be-a42a-c7cd29b1bb2f)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/9a10f00f-1a4c-4dbb-9386-1959acbe49b8)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/8f054238-d0a0-4088-9cc1-6d5cbd839423)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/3b6ce526-36b5-4b1f-a3f2-c3a6e93a634c)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/5f400bc3-5bec-4bd0-90dd-8e3868c6d969)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/f6ea6335-2d70-4ed2-9ccf-fde3753da4fe)

2. Make sure that all data in the screenshots above is connected to the backend.

# Acceptance Criteria
1. Follow all above requirements
2. Double check it, change data from database to see if its connected to backend

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/520-feature-connect-public-listing-property-single-view-to-backend
PR: https://github.com/explore-siargao/es-main/pull/575
