### ISSUE TITLE
[Feature] Connect public listing activity single view to backend

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#522]
# Requirements
1. connect  `/listing/activity/1` page to backend api getActivityById
![Image](https://github.com/explore-siargao/es-main/assets/29083384/60f2620f-480f-40e2-a8da-eec29b55f802)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/a2940a6d-3f87-4492-923c-8961462f60b9)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/0c6afaa7-ae7a-4a4e-b0e7-6dc3b97615ec)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/fbae214f-71ea-40c0-ae99-cc2432381af5)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/2f76a9e9-322e-4c46-99af-6fc1fdd7b9a5)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/bb21a5d2-b27f-491a-b50d-286171bd61e2)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/bf9a98bf-eef8-44e2-baeb-a427ffbd356c)
![Image](https://github.com/explore-siargao/es-main/assets/29083384/658c6631-356e-4b84-920d-ff33849c5961)

2. Make sure that all data in the screenshots above is connected to the backend.

# Acceptance Criteria
Follow all above requirements
Double check it, change data from database to see if its connected to backend

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/522-feature-connect-public-listing-activity-single-view-to-backend
