### ISSUE TITLE
[Story] On bed and room name make it select with custom input

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#536]
# Requirement
1. When selecting a name or bed in a unit, use the drop-down menu with custom inputs.
2. If the name of the bed is not available in the drop-down menu, use the custom input option.
![image](https://github.com/explore-siargao/es-main/assets/29083384/9bd990df-06df-4a63-9407-5c88262ee057)
3. Place the custom input in top of drop down menu
4. This also applies to the bed drop-down.
![image](https://github.com/explore-siargao/es-main/assets/29083384/1dc42445-90e1-4d82-b282-fa75ae738a20)
![image](https://github.com/explore-siargao/es-main/assets/29083384/ba99b30a-1bb3-41c2-b674-67b202fd90dc)

# Acceptance Criteria
Test all requirements above to ensure all need functions and UI is working properly

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/536-story-on-bed-and-room-name-make-it-select-with-custom-input
PR: https://github.com/explore-siargao/es-main/pull/539
