### ISSUE TITLE
[Bug] Bed name and room name custom input not auto select after creation

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#546]
# Requirement
Make sure that after creating new slelect option in bed name and room name it will be automatic selected option

# Acceptance Criteria
Fixed the error described in requirement above.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/546-bug-bed-name-and-room-name-custom-input-not-auto-select-after-creation
