### ISSUE TITLE
[Story] Put all the maps in modal

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#549]
# Requirement 
1. Remove the disable and enable of map on Click
2. Put the map on modal
3. Add a link or button that will show the map to edit 
4. Add button that will handle the saving and closing of the map
![image](https://github.com/user-attachments/assets/a64e7d6d-8d0f-4744-a2da-26e40339e413)

# Acceptance Criteria
1. Test all needed function

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/549-story-put-all-the-maps-in-modal
