### ISSUE TITLE
[Bug] Make it again a dropdown then the last choice is custom

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#550]
# Reqyurement
1. In select if they choose custom input will appear in the bottom of select.
2. Make sure that the input will connect to payload of backend.

![Untitled](https://github.com/user-attachments/assets/7468b029-9ab6-4834-b338-d551a15bc67d)

# Acceptance Criteria
1. Make sure all requirements aboved is followed
2. Test the functionality to see all is working properly

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/550-bug-make-it-again-a-dropdown-then-the-last-choice-is-custom
