### ISSUE TITLE
[Story] Add Margin 8 for all inputs in setup all categories

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#551]
# Requirements
1. Add margin top in all inputs for all setup categories except for the first inputs

# Acceptance Criteria 
1. Double check all inputs on all setup in different categories(Property, Rental and Activity) if met needed requirement.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/551-story-add-margin-8-for-all-inputs-in-setup-all-categories
