### ISSUE TITLE
[Story] Create custom components for different inputs version 2

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#559]
# Requirements
1. Create the following custom components
- Input2
- TextArea2
- Select2

2.  Use this as a pattern 
https://pastebin.com/fzQqcS34

3. The code pattern is for Input2, apply the same logic on TextArea2 and Select2

# Acceptance Criteria
1. Make sure you follow all above requirements
2.  Test it all if met the requirements needed

**Comment by jpmadrigal07** [comment]
For refinement

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/559-task-create-custom-components-for-different-inputs-version-2
PR: https://github.com/explore-siargao/es-main/pull/1008
