### ISSUE TITLE
[Story] Apply the map logic onclick of category location setup to activity itinerary

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#568]
# Requirements
1. Apply the onclick logic of category setup location on map in activity itinerary map
![image](https://github.com/user-attachments/assets/e6e10c2d-38a4-404a-932b-9529819d1a82)

# Acceptance Criteria
1. Do the above requirements and test it.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/568-story-apply-the-map-logic-onclick-of-category-location-setup-to-activity-itinerary

PR: https://github.com/explore-siargao/es-main/pull/571
