### ISSUE TITLE
[Bug] Fix error on saving editing segments

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#574]
# Requirements
1. Fix the error on editing itinerary segments when editing it the payload only receive the previous segments not getting the new segments.

# Acceptance Criteria
1. Make sure that the error found in requirements is fixed and tested

# Tasks(if any)

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/574-bug-fix-error-on-saving-editing-segments
