### ISSUE TITLE
[Feature] Modify Create property unit modal

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#580]
# Requirements
1. Change the title and description of menu buttons. See the image below.

![Image](https://github.com/user-attachments/assets/a6562b67-951b-407d-ae5b-06f0c8b5a4dc)

New Title and description
New shared space:
A bed in a dorm room or shared accommodation with shared amenities

New private room:
A private room or sleeping space that might have a shared bathroom or kitchen.

New whole space:
A fully self-contained accommodation such as a villa, apartment or bungalow with its own bathroom, kitchen, and living area.
# Acceptance Criteria
Double check all buttons if its still working properly after modifications.

# Tasks(If any)

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/580-feature-modify-create-property-unit-modal
