### ISSUE TITLE
[Feature] Modify Add shared space/beds page ui

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#582]
# Requirements
1. Mofify the UI and functions of beds/shared spaces
2.  See the image below fo reference
![Untitled-1](https://github.com/user-attachments/assets/1182178c-8f28-49f4-a4a3-418490a7c862)

# Acceptance Criteria
Do the following requirements above and Test it.
# Tasks(if any)

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/582-feature-modify-add-shared-spacebeds-page-ui
