### ISSUE TITLE
[Story] Add filter to earnings

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#587]
# Requirements
Add the following filters in earnings UI
- Month
- Year
- Categories
For more information look for this video
https://drive.google.com/file/d/1zPMLrNen-UQc2apyksGoybdpXlXNwMmQ/view

# Acceptance Criteria
Make sure that all filters needed in Earnings page is added.

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/587-story-add-filter-to-earnings
PR: https://github.com/explore-siargao/es-main/pull/607
