### ISSUE TITLE
[Bug] Fix error on Activity Box UI

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#594]
# Requirements 
1. Fix the error found in activity public single page caused by activity box ui. See the image below for error reference.
![image](https://github.com/user-attachments/assets/1ba7ad88-fa3b-4856-8a05-1d9e29cbd47f)

# Acceptance Criteria
Make sure to fix the error showed on image above.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/594-bug-fix-error-on-activity-box-ui
