### ISSUE TITLE
[Story] Create reusable minimap search ui

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#603]
# Requirements

THIS IS BLOCKED BY #625, IT NEEDS TO BE FINISHED FIRST. 

1. Create a reusable component that contain a small map.
2. See the example below.
![image](https://github.com/user-attachments/assets/9d5d2eef-9a26-4933-9087-efeef4c5862b)

# Acceptance Criteria
Do the following requirements above and test it.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/603-story-search-using-mini-map-ui
PR: https://github.com/explore-siargao/es-main/pull/659
