### ISSUE TITLE
[Story] Create custom components for essential travel information

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#605]
# Requirements
![image](https://github.com/user-attachments/assets/992e4f56-1480-4012-8be0-1eba7fa9f8ac)
1. Create reusbale components like on image above
2. All inside components is dynamic
- title
- description
- groupCards = [{imageKey, mainPlace, subPlace, url}]
3. Contain next and previous button to slide to left and right

# Acceptance Criteria
Do all the requirements above and test it

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/605-story-create-custom-components-for-essential-travel-information
