### ISSUE TITLE
[Story] Create component for bottom part of home page

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#606]
# Requirements
![image](https://github.com/user-attachments/assets/37bd23fa-395f-40ab-8902-341efdb61000)

1. Create a  reusable card component that will handle the information needed 
2. component contains the following dynamic props
- imageKey
- title
- description
- linkTitle
- url

# Acceptance Criteria
Do all above requirements and test it.

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/606-story-create-component-for-bottom-part-of-home-page
PR: https://github.com/explore-siargao/es-main/pull/616
