### ISSUE TITLE
[Story] Create component for browse property types cards list

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#608]
# Requirements
![image](https://github.com/user-attachments/assets/593b6be1-0135-44d0-8fb5-7fa3991c31b0)
1. Create a component that will be look like on the image above.
2. This component contains the following props
- title
- description
- cardGroup = [{imageKey, cardTitle, url}]
3. User can slide from left to right and back to left using next and previous button
4. If the user click single item it will redirect to the url provided on props

# Acceptance Criteria
Do and test the following requirements above.

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/608-story-create-component-for-browse-property-types-cards-list
PR: https://github.com/explore-siargao/es-main/pull/619
