### ISSUE TITLE
[Story] Create search section component for landing page

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#611]
# Requirements
1. Create a search section component for home landing page
2. See the image below for the whole example
![image](https://github.com/user-attachments/assets/c7964d02-53a3-4182-a15d-a38071c905c2)
3. On actual search bar see the image below.
![image](https://github.com/user-attachments/assets/4a5399ae-ef46-4318-99d8-87f893e22dd8)
4. Search section will have background overlay image, we will pick any of these
![image](https://github.com/user-attachments/assets/888129d7-c9e0-4fac-bfde-a8abc8abda7e)
![image](https://github.com/user-attachments/assets/ca603735-9b7b-42c8-a14b-70dd247ca6e1)
![image](https://github.com/user-attachments/assets/5da9ac07-0bef-436d-96a6-7459fb785e32)

# Acceptance Criteria
Do the requirements above and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/611-story-create-search-section-component-for-landing-page
PR: https://github.com/explore-siargao/es-main/pull/627
