### ISSUE TITLE
[Story] Change guide url route

### ISSUE THREAD

**Issue by jpmadrigal07** [explore-siargao/es-main#624]
# Requirements
1. Change the url route from `/guide/surf/[surf-name]` to `/guides/surfing/[surf-name]`
2. Change the url route from `/guide/restaurant/[restaurant-name]` to `/guides/restaurants/[restaurant-name]`
3. Change the url route from `/guide/travel/[travel-name]` to `/guides/locations/[location-name]`

# Acceptance Criteria
Sample pages of each category must still work with this route changes

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/624-story-change-guide-url-route
PR: https://github.com/explore-siargao/es-main/pull/626
