### ISSUE TITLE
[Story] Connect guide pages to landing page

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#629]
# Requirements
![image](https://github.com/user-attachments/assets/37bd23fa-395f-40ab-8902-341efdb61000)

1. On landing page you will see this in bottom part of the page
2. connect each card to the link of every guides
- Srurfing guides - `/guides/surfing/[surf-name]`
- Restaurant, cafe aand bars guide - `/guides/restaurants/[restaurant-name]`
- location guide - `/guides/locations/[location-name]`

# Acceptance Criteria
Do the above requirements and test it

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/629-story-connect-guide-pages-to-landing-page
PR: https://github.com/explore-siargao/es-main/pull/634
