### ISSUE TITLE
[Story] Add quantity to shared room

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#636]
# Requirements
![image](https://github.com/user-attachments/assets/228a27a4-c097-4e08-b17c-66396feec7ac)

1. Add input that will accept number
2. The label of input will be "How many of this type you have?"
3. Adjust the backend make sure that the quantity will save to database.

Example::
![image](https://github.com/user-attachments/assets/ffd67709-5e73-487c-819b-99757dae45ff)

# Acceptance Criteria
Do and test all the requirements above

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/636-story-add-quantity-to-shared-room
PR: https://github.com/explore-siargao/es-main/pull/642
