### ISSUE TITLE
[Story] Remove description to units list

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#637]
# Requirements
![image](https://github.com/user-attachments/assets/a261181e-ac0e-4782-82d1-e811f796b7cf)
1. Remove the decription column in unit list table.
2. Delete also the description field in model of unitType

# Acceptance Criteria
Do and test all the requirements above.

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/637-story-remove-description-to-units-list
PR: https://github.com/explore-siargao/es-main/pull/640
