### ISSUE TITLE
[Story] Create reusable checkBoxFilter component

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#643]
# Requirements
1. Create reusable checkbox that will use in filtering bookable units on home page.
2. The interface of checkbox will be look like of photo below.
![image](https://github.com/user-attachments/assets/e2080c82-9b91-4280-82ca-e0c2e3252f6e)
3. This component will use to set value in suzstand.
# Acceptance Criteria
Do and test all the requirements above.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/643-story-create-reusable-checkboxfilter-component
PR: https://github.com/explore-siargao/es-main/pull/658
