### ISSUE TITLE
[Story] Create reusable adjustableFilter component

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#644]
# Requirements
1. Create reusable adjustable component that will use in filtering bookable units on home page.
2. The interface of adjustable component will be look like of photo below.
![image](https://github.com/user-attachments/assets/8f569d1a-c830-4c6a-838a-22a060a5d60b)
3. This component will use to set value in suzstand.
4. See an example on booking.com
# Acceptance Criteria
Do and test all the requirements above.

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/644-story-create-reusable-adjustablefilter-component
PR: https://github.com/explore-siargao/es-main/pull/665
