### ISSUE TITLE
[Story] Create reusable numericFilter component

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#645]
# Requirements
1. Create reusable numeric component that will use in filtering bookable units on home page.
2. The interface of numeric component will be look like of photo below.
![image](https://github.com/user-attachments/assets/27b39f79-0a43-483e-bb19-b11af850f706)
3. This component will use to set value in suzstand.
# Acceptance Criteria
Do and test all the requirements above.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/645-story-create-reusable-numericfilter-component
PR: https://github.com/explore-siargao/es-main/pull/660
