### ISSUE TITLE
[Story] Add qty to rentals motorcycle and bikes UI  and backend

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#648]
# Requirements
1. Add qty input in adding rental motorcycle and bike. 
![image](https://github.com/user-attachments/assets/5831a7a9-91f6-4e8a-98a1-421e8dee0a41)
3. On Car do not add qty input.
4. Adjust the backend of rentals, add optional qty
5. Make sure that if you add motorcycle and bike qty will save to database same on other dats
6. Add the input in Basic info
![image](https://github.com/user-attachments/assets/4ab809d3-63ab-4722-8bd1-dec9bd47ea3f)

# Acceptance Criteria
Do and test above requirements and test it

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/648-story-add-qty-to-rentals-motorcycle-and-bikes-ui-and-backend
