### ISSUE TITLE
[Story] Complete home page UI

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#651]
# Requirements
1. Create reusable component that will use as item of slider
![image](https://github.com/user-attachments/assets/9b05d7a3-9cfa-4910-8b65-ca543f6d630e)
2. in reusable slider use the newly reuable component
3. In What your travel style remove the exist items only the first 4 item will remain.
4. Add slider with items in this 3
![image](https://github.com/user-attachments/assets/fe49c8cf-a3a3-4da5-a8f4-96096d0cdc02)

# Acceptance Criteria
Do all the requirements above and test

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/651-story-complete-home-page-ui
PR: https://github.com/explore-siargao/es-main/pull/664
