### ISSUE TITLE
[Story] Explore siargao islands page

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#652]
# Requirements
1. url of the page will be /locations/:location-name
2. create a new page that contains all properties, activities and rentals in specific location
![Untitled](https://github.com/user-attachments/assets/9da5c7f4-7553-4b71-8ba4-6a130f5d5f0a)
3. On header of the page use the hero section reusable component
4. Create new reusable component for hero section
![Screenshot 2024-07-31 140250](https://github.com/user-attachments/assets/a6258656-d639-4c49-9c82-01badbae9fd4)

# Acceptance Criteria
Do and test all above requirements

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/652-story-explore-siargao-islands-page
