### ISSUE TITLE
[Story] Travel style page

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#653]
# Requirements
1. url of the page will be /properties/:category
2. create a new page that contains all bookings depends on category
![traavel sty;e](https://github.com/user-attachments/assets/ee047043-0d02-414b-9547-9cc5404fea07)
3. Connect this to home page ui
# Acceptance Criteria
Do all the requirements above and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/653-story-travel-style-page
PR: https://github.com/explore-siargao/es-main/pull/668
