### ISSUE TITLE
[Story] Add cuisine in restaurant guide map popup pin

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#656]
# Requirements
1. Add restaurant type of cuisine in restaurant guide map popup box when hovering on pin
![Screenshot 2024-08-05 153359](https://github.com/user-attachments/assets/2603e040-d8f8-4a7a-95e0-755b82ac7972)
2. The term "restaurant type of cuisine" refers to the specific style or tradition of cooking that a restaurant specializes in. Cuisines are often associated with particular countries or regions and encompass the ingredients, techniques, and dishes that are typical of those areas.( e.g. "Pizza", "Pasta","Litchong baboy")

# Acceptance Criteria
Do and test all requirements above.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/656-story-reliable-cars-motorbikes-and-more-page
PR: https://github.com/explore-siargao/es-main/pull/675
