### ISSUE TITLE
[Feature] Payload cms for surfing

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#672]
# Requirements
1. Analyze all needed fields in surfing guides
2. Create a payloadcms for guide surfing base from result of analization.
3. Apply the surfing payload cms to the frontend of surf guide blog

# Acceptance Criteria
Do and test all above requirements

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/672-feature-payload-cms-for-surfing
PR: https://github.com/explore-siargao/es-main/pull/695
