### ISSUE TITLE
[Feature] Payload cms for for restaurants

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#673]
# Requirements
1. Analyze all needed fields in restaurant guides
2. Create a payloadcms for guide restaurant base from result of analization.
3. Apply the restaurants payload cms to the frontend of restaurant guide blog

# Acceptance Criteria
Do and test all above requirements

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/673-feature-payload-cms-for-for-restaurants
PR: https://github.com/explore-siargao/es-main/pull/751
