### ISSUE TITLE
[Feature] Payload cms for location directions

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#674]
# Requirements
1. Analyze all needed fields in location guides
2. Create a payloadcms for guide locations base from result of analization.
3. Apply the locations payload cms to the frontend of restaurant guide blog

# Acceptance Criteria
Do and test all above requirements

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/674-feature-payload-cms-for-location-directions
PR: https://github.com/explore-siargao/es-main/pull/759/
