### ISSUE TITLE
[Story] Create reusable component for the filter result

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#679]
# Requirements
1. Create reusable component that will accept props of array of cards
2. Also accept props of filter payloads
3. Output will be look like this
![filter result](https://github.com/user-attachments/assets/cf8914e1-38dc-4894-b2b2-08c3c98734c6)
4. This component is responsive

# Acceptance Criteria
do and test all above requirements

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/679-story-create-reusable-component-for-the-filter-result
