### ISSUE TITLE
[Story] Connect main landing page to second page

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#680]
# Requirements
1. Connect all related items to landing page second level from main landing page.
2. Make sure if user clicked spefic items  it will go go to filtered page/ 2nd level home page

# Acceptance Criteria
Do all the above requirements and test it.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/680-story-connect-main-landing-page-to-second-page
