### ISSUE TITLE
[Story] Create dynamic second level page

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#681]
# Requirements
1. Create new page for result filter
2. url of page will look like this /listings?type=property&type=rental&location=malinao
3. The url can add more searchParams not only on example given
4. On this page combine the side filter and result filter components left side is the side filter and on right side is the result

## Sketched output
![2nd page](https://github.com/user-attachments/assets/706b685a-fa0e-4fac-9d92-89be359788da)

# Acceptance Criteria
Do and test all the above requirements.

**Comment by alkejah** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/681-story-create-dynamic-second-level-page
