### ISSUE TITLE
[Feature] Guide map change favicon

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#730]
# Requirements
1. Change the favicon in the map of different giudes
![Screenshot 2024-08-13 153535](https://github.com/user-attachments/assets/f1e403c5-93e5-44f5-95dd-4636bd196b41)

Surfing
![Image](https://github.com/user-attachments/assets/71139c17-1f64-43c2-973d-681b27b3ff52)

Restaurant
![Image](https://github.com/user-attachments/assets/16973b0d-e701-4191-a903-7aca86ff780c)

Activities, Property and Rental
![Image](https://github.com/user-attachments/assets/2d97e347-d896-4e69-bfda-d55c383f2ecb)

# Acceptance Criteria
Do and test all the requirements above

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/730-feature-guide-map-change-favicon
PR: https://github.com/explore-siargao/es-main/pull/860
