### ISSUE TITLE
[Story] All content same margin including search bar

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#733]
# Requirements
1. Make the margin of search and contents are in same margin
 ![Screenshot 2024-08-14 103332](https://github.com/user-attachments/assets/71fd44d8-ee63-4f36-afb9-a7e69b2268bb)
2. make the items columns 3 or 4 in content of filters

# Acceptance Criteria
Do all the requirements above and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/733-story-all-content-same-margin-including-search-bar
PR: https://github.com/explore-siargao/es-main/pull/766
