### ISSUE TITLE
[Story] Edit side filter make it standout

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#734]
# Requirements
1. Adjust the filter UI make it standout
2. Make the filter component is dynamic
Example: When I click one rental item from landing page it will go to rental 2nd page and show on the filter and the type of rental is checked in filter. Then the property and activities filter will not available there

# Acceptance Criteria
Do all the requirements above and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/734-story-edit-side-filter-make-it-standout
PR: https://github.com/user-attachments/assets/267a2c36-df23-44da-b6df-df6250f42127)](https://github.com/explore-siargao/es-main/pull/774
