### ISSUE TITLE
[Feature] Create Terms and use UI in public pages

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#752]
# Requirements
1. Needs to be public page
2. Content needs to be on CMS and can be edited in CMS
3. User blank page with the default header and footer for Guest
4. This is the content
https://etchrlab-my.sharepoint.com/:w:/g/personal/jake_etchrlab_onmicrosoft_com/Ec8Uz7WJlPxNm-sgj0vISSIBL7k6dAJXmOr7iTUhaYYdmw?e=q0p3Dj
5. Content needs to be added to the CMS
6. Slug will be `/terms-and-use` and can be access in `/legal/terms-and-use`
7. Page that will be created in Next.js app will be `/legal` and the pages under that will be dynamic `/legal/[legal-name-from-cms]`
8. CMS collection name is `Legal`

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/752-feature-create-terms-and-use-ui-in-public-pages
PR: https://github.com/explore-siargao/es-main/pull/858
