### ISSUE TITLE
[Feature] Surf and Restaurant Guide UI Adjustments

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#753]
# Requirements
See the pdf file below all needed agdjustment in Restaurant Guide UI is there.
[Notes for clean up UI for restaurants guide page.pdf](https://github.com/user-attachments/files/16608169/Notes.for.clean.up.UI.for.restaurants.guide.page.pdf)

# Acceptance Criteria
Do the above requirements and test it.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/753-feature-surf-and-restaurant-guide-ui-adjustments
PR: https://github.com/explore-siargao/es-main/pull/763
