### ISSUE TITLE
[Story] Landing and 2nd page UI Adjustments

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#784]
# Requirements
## Landing page
1. Adjust items on header place items on right side
![image](https://github.com/user-attachments/assets/755ec65c-bd61-449e-ad44-143a40cba34d)
2. Landing page margin items make sure its align to other items
![image](https://github.com/user-attachments/assets/90f186cc-59de-4e17-b602-90098c073cad)

## 2nd page
1. Remove the here section and make the search bar is below the header
![image](https://github.com/user-attachments/assets/9f0e1b94-b3b1-457e-8826-a7ded6f32077)
See example below
![WhatsApp Image 2024-08-16 at 16 19 31_fdba3283](https://github.com/user-attachments/assets/5c5e0ebf-d3f6-4964-88d3-a28190d6a158)

# Acceptance Criteria
D and test all above requirements

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/784-story-landing-and-2nd-page-ui-adjustments
PR: https://github.com/explore-siargao/es-main/pull/802
