### ISSUE TITLE
[Story] Guides surf UI adjustments

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#785]
# Requirements
1. Guide header is full width
![image](https://github.com/user-attachments/assets/2ef631f0-ae0f-47d1-ba5a-fdad3634e84d)
2.  Arrangement will be Header->Search->Nearby

# Acceptance Criteria
Do and test above requirements to complete this ticket.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/785-story-guides-surf-ui-adjustments
PR: https://github.com/explore-siargao/es-main/pull/833
