### ISSUE TITLE
[Story] Guide restaurants UI adjustments

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#786]
# Requirements
1. Remove about section
![image](https://github.com/user-attachments/assets/ad9b7e66-0ee9-4e24-8d60-0e0838ac0107)
2. Make the social medias is icon types only
# Acceptance Criteria

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/786-story-guide-restaurants-ui-adjustments
PR: https://github.com/explore-siargao/es-main/pull/804
