### ISSUE TITLE
[Story] Guides travel UI adjustments

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#787]
# Requirements
1. On Guide Travel fix the margin problems
2. Make the travel side popular guides and page summary scrollable
![image](https://github.com/user-attachments/assets/c3e9c2fa-c5f1-4a64-9c8f-a8a30f61251c)

# Acceptance Criteria
Do all abovevrequirements and test it

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/787-story-guides-travel-ui-adjustments
PR: https://github.com/explore-siargao/es-main/pull/808
