### ISSUE TITLE
[Story] Lightbox UI Adjustments

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#788]
# Requirements
1. On lightbox show label of image counts like 1 of 10 images
![image](https://github.com/user-attachments/assets/0d7ff253-1e4b-4a6a-9af9-23b62ae067af)
2. Connect it to backend 
# Acceptance Criteria
Do and test all above requirements

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/788-story-lightbox-ui-adjustments
PR: https://github.com/explore-siargao/es-main/pull/801
