### ISSUE TITLE
[Story] Update rental rates endpoint

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#8]
Convert the mock endpoint for update rental rates endpoint to api v2.

**Comment by jpmadrigal07** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/8-story-update-rental-rates-endpoint

**Comment by ramil25** [comment]
PR: https://github.com/explore-siargao/es-main/pull/15
Branch: https://github.com/explore-siargao/es-main/tree/8-story-update-rental-rates-endpoint
