### ISSUE TITLE
[Feature] Create tabs for rental and properties calendar

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#830]
# Requirements
1. Create a tab in the calendar pages that separate each categories
2. See image below to see where to position the tabs
![image](https://github.com/user-attachments/assets/d9231f50-ecf0-462c-82ab-4b8c48c3ac1e)
3. Apply this to rentals, properties and activities

# Acceptance Criteria
Do all the requirements above and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/830-feature-create-tabs-for-rental-and-properties-calendar
PR: https://github.com/explore-siargao/es-main/pull/837
