### ISSUE TITLE
[Hotfix] Change to webURL all localhost url on guides pages

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#839]
# Requirements
Change all the URL localhost:3000 to contstant variable WEB_URL in all guide pages
See the image below for reference

Wrong URL
![Image](https://github.com/user-attachments/assets/0b13868f-201f-4753-b812-e589b8376d04)

Correct URL
![Image](https://github.com/user-attachments/assets/11740dc9-0fac-464a-9b85-cbd9907af0eb)

# Acceptance Criteria
See the requirements aabove and fix it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/839-hotfix-change-to-weburl-all-localhost-url-on-guides-pages
PR: https://github.com/explore-siargao/es-main/pull/841
