### ISSUE TITLE
Convert guide pages fetch to server side

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#840]
# Requirements
No `useEffect` for fetching. Fetch need to happen in `page.tsx` file.

Reference:
https://github.com/jpmadrigal07/filinvest/blob/master/apps/land/app/article/%5BnewsId%5D/page.tsx

Use the pattern in the link above specifically the `getNewsContent` function. But in our app, it needs to be reusable so that the fetch can be use by all guides and blogs.

# Acceptance Criteria

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/840-convert-guide-pages-fetch-to-server-side
PR: https://github.com/explore-siargao/es-main/pull/898
