### ISSUE TITLE
[Bug] Lightbox fix height of bottom image

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#846]
# Requirements
Fix the error on lightbox that the size of images in buttom part is the fix to one size. See image below
![321](https://github.com/user-attachments/assets/b86d53a9-37cc-4a00-bbac-8d1bbbecd576)

# Acceptance Criteria
Do above requirements and test it.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/846-bug-lightbox-fix-height-of-bottom-image
PR: https://github.com/explore-siargao/es-main/pull/848
