### ISSUE TITLE
[Story] Add divider on user dropdown menu on header

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#851]
# Requirements
1. Add other menu in dopdown
![image](https://github.com/user-attachments/assets/403d89d4-6ca3-4c44-add6-36cfb552758f)
3. Put Divider in each different section in the menu

See image below for pattern
<img width="506" alt="122" src="https://github.com/user-attachments/assets/f8516707-b3aa-4ec3-b408-695a014096c2">

# Acceptance Criteria
Do all above requirements and test it.

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/859
Branch: https://github.com/explore-siargao/es-main/tree/851-story-add-divider-on-user-dropdown-menu-on-header
