### ISSUE TITLE
[Story] Tabs for rentals will be show only the type that has items

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#853]
# Requirements
Make sure that the tab on rentals clendar is dynamic if theres no rentay types offer by host tab will be not available.
Example if the host only have Car and Motorcycle offers the tab will show is only Car and Motorcycles

# Acceptance Criteria
Do above requirements and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/853-story-tabs-for-rentals-will-be-show-only-the-type-that-has-items
PR: https://github.com/explore-siargao/es-main/pull/867
