### ISSUE TITLE
[Story] Legends for calendar priorities need to apply the initial ui

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#854]
# Requirements
1. Create a legends UI for the calendar.
2. Put it in the bottom of calendars See example image below
![littlehotelier-bookings-min](https://github.com/user-attachments/assets/406acf21-a162-495e-b641-00b6bc46cb28)
3. This colors will be apply to legends
Primary - Corfirmed
Red - Out of service
In House - Secondary
Blue- Checked out
Gray - Blocked Dates
Orange - Others
4. Create also a modal for this
5. 
<img width="776" alt="Screenshot_2024-08-28_at_1 43 42_PM" src="https://github.com/user-attachments/assets/c0bee7b1-2ced-44c6-aeb9-1f4c60dd8c83">

6. If you clicked the legend below modal will show for legends

# Acceptance Criteria
Do all the requirements above and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/854-story-legends-for-calendar-priorities-need-to-apply-the-initial-ui
PR: https://github.com/explore-siargao/es-main/pull/869
