### ISSUE TITLE
[Story] Property units types need to be specific to the property

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#856]
# Requirements
1. Follow unit types base from property type. See the excel below.
![image](https://github.com/user-attachments/assets/00839149-7f39-4c6f-8cd4-a67b61a9b4e6)
![image](https://github.com/user-attachments/assets/e71680b7-4c85-45a9-a43a-4d840d1b21ba)
![image](https://github.com/user-attachments/assets/608ab30a-902c-4466-8d0b-a59ddabf564c)
![image](https://github.com/user-attachments/assets/4dd67495-0879-4549-925e-18701909bbfc)

# Acceptance Criteria
Do all the requirements abve

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/issues/856
PR: https://github.com/explore-siargao/es-main/pull/935
