### ISSUE TITLE
[Story] Connect frontend to backend property calendar reservations

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#865]
# Requirements
1. Using the custom hooks connect the frontend of calendar property to backend
2. I Need some modification in frontend do it.

# Acceptance Criteria
Do all above requirements and test it.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/865-story-connect-frontend-to-backend-property-calendar-reservations
PR: https://github.com/explore-siargao/es-main/pull/876
