### ISSUE TITLE
[Feature] Implement Legends to rental and properties

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#875]
# Requirements 
1. Implement created legends and legends modal to property and rentals
2. Update legends base from jake recommendations
# Acceptance Criteria
Do the above requirements and test it.

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/875-feature-implement-legends-to-rental-and-properties
PR: https://github.com/explore-siargao/es-main/pull/880
