### ISSUE TITLE
[Story] All inputs radius standard

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#882]
# Requirements
1. Inputs and selects radius needs to be standard
2. Do you have any sleeping spaces section margin bottom
3. Capitalize on the Typography component (Only the first letter is capital)

# Acceptance Criteria
Do all the above requirements

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/882-story-all-inputs-radius-standard
PR: https://github.com/explore-siargao/es-main/pull/885
