### ISSUE TITLE
[Story] Listing units pagination

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#884]
# Requirements
1. Make a pagination for units list
2. See the the below image for reference.
![paginate](https://github.com/user-attachments/assets/22e5048a-f2cb-4fb0-bb53-f1cddfeb4861)
3. Make the pagination for property and activity  listings work, use the rental listing for reference.
# Acceptance Criteria
Do the above task and test it.

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/886
Branch: https://github.com/explore-siargao/es-main/tree/884-story-listing-units-pagination
