### ISSUE TITLE
[Story] Modified existing guide search

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#891]
# Requirements
Watch the video starts on 21:05 to 24:23 for jake instructions
https://drive.google.com/file/d/19tBDgtyl-BsdwfZTbhDEn0_yws8J7YeG/view
# Acceptance Criteria
Do the above requirements and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/891-story-modified-existing-guide-search
PR: https://github.com/explore-siargao/es-main/pull/912
