### ISSUE TITLE
[Story] Change guides urls slugs

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#897]
# Requirements
1. Change the locations to travel
2. On surfing the URI will be `/siargao/surfing/guides/[name]`

# Acceptance Criteria
Do the above task and test it

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/948
Branch: https://github.com/explore-siargao/es-main/tree/897-story-change-guides-urls-slugs
