### ISSUE TITLE
[Cleanup] Listing main public page

### ISSUE THREAD

**Issue by jpmadrigal07** [explore-siargao/es-main#899]
Go to this link: [http://localhost:3000/listing/property/6673ce299e14de78e4869777](http://localhost:3000/listing/property/6673ce299e14de78e4869777)

1. Make the margin universal

2. Make the photos rounded, reuse what we have in cms if we can
![image](https://github.com/user-attachments/assets/f6e5cfce-6d00-448a-b3af-1534647ecdba)

3. Lightbox is not showing
![image](https://github.com/user-attachments/assets/5b3d7638-9e43-466f-acde-443ef145b958)

4. Make sure we use the universal error message if nothing's found
![image](https://github.com/user-attachments/assets/5d5de7af-7240-4a1b-8981-27a82bde4659)

5. Check those error in activity and rental also

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/899-cleanup-listing-main-public-page
PR: https://github.com/explore-siargao/es-main/pull/903
