### ISSUE TITLE
[Story] Click to expand legends and rental calendar tabs 

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#908]
# Requirements
1. On the left side of Confirmed legends add a label "Click to expand lefends"
2. On the rental tabs make it dynamic hovering see the video below for jake instructions.
https://drive.google.com/file/d/1asfyx27qRkGyRraghsow__PlTzI5EU-m/view
Start time: 13:33
End Time : 14:20
 
# Acceptance Criteria
Do all the above requirements and test it

**Comment by kinnethjavier** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/908-story-click-to-expand-legends-and-rental-calendar-tabs
PR: https://github.com/explore-siargao/es-main/pull/914
