### ISSUE TITLE
[Story] Change Villa to Whole Place in Property type selections.

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#915]
# Requirements
1. Change the Villa in property type UI to Whole place.
2. If you choose the  Whole place property type on creating new units it will direct to edit whole place UI.
# Acceptance Criteria

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/926
Branch: https://github.com/explore-siargao/es-main/issues/915
