### ISSUE TITLE
Currency support

### ISSUE THREAD

**Issue by jpmadrigal07** [explore-siargao/es-main#916]
•⁠  PHP
•⁠  ⁠USD
•⁠  ⁠SKW
•⁠  ⁠⁠EUR
•⁠  ⁠⁠AUD
•⁠  ⁠⁠ILS
•⁠  ⁠⁠GBP

**Comment by jpmadrigal07** [comment]
![image](https://github.com/user-attachments/assets/5b5e044a-d130-4457-8188-c4b1fb84f14a)

**Comment by Dyayy026** [comment]
Currency converter using currency.js
link: https://drive.google.com/file/d/1yW6AIHrgYrJP7s93yjffTSCwVTdVx1rs/view?usp=drive_link
