### ISSUE TITLE
[Story] Whole place unit logic modification

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#953]
## 🌈 Objective

As a User host\
I want to be able to add new units on property that the type is Whole place
So that I'll be able to have multiple whole place offers.

### Requirements
1. Create a modal that shows a list of unit types the host can offer.
2. Once the host chooses the unit type they want to offer, they will be redirected to the whole place setup page.
3. On the setup page for the whole place, the unit type dropdown will be disabled, and it will display the unit type the host selected in the modal.
4. Once the host adds one unit to the whole place, the next time they add a new unit, the modal will not appear again.
5. If you add a new whole place in that property, the unit type will be the same as the previously added unit.

### Design Workflow
![image](https://github.com/user-attachments/assets/f009ce32-64cf-4bb8-827e-d97d1a13d268)
![Screenshot 2024-09-09 120257](https://github.com/user-attachments/assets/ade51fdb-497a-4602-aa76-0e216bd3e45c)

## 🚨 Out of Scope
1. Fixing bugs for adding new whole place

## 🗒️ Other notes
1. use the useGetPropertById for the logic of checking units length

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/953-story-whole-place-unit-logic-modification
PR: https://github.com/explore-siargao/es-main/pull/980
