### ISSUE TITLE
[Story] Change the Room name inputs same on whole place when adding beds and add bath room and amenities

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#967]
## 🌈 Objective

As a User host\
I want to be able to add multiple types and counts of beds in unit rooms
So that I'll be able to add multiple beds in rooms at the same time.

### Requirements
1. Change the setup UI for adding beds in rooms same on whole place add beds on living room.
2. Add Field where Asking for the room has shared bathrrom, aswerable by Yes or No
3. Add Field where asking for the room has shared amenities, answerable by Yes or No 
4. Adjust the backend for adding beds in rooms same on adding whole place add beds on living room and other additional data.
5. Modify the hooks that connected to this.

### Design Workflow
![Screenshot 2024-09-09 164742](https://github.com/user-attachments/assets/861d2145-083f-483d-a820-1e4af910d104)

## 🗒️ Other notes

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1015
Branch: https://github.com/explore-siargao/es-main/tree/967-story-change-the-room-name-inputs-same-on-whole-place-when-adding-beds-and-add-bath-room-and-amenities
