### ISSUE TITLE
[Story] Change the position of title field in whole place setup

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#968]
## 🌈 Objective

As a User Host\
I want to be able to see the correct arrangements of inputs in whole place listing setup\
So that I'll be able to organize and manage all necessary fields

### Requirements
1. Change the position of title fields put it after Bedroom field
2. Add descriptive text for unit type.

### Design Workflow
![Screenshot 2024-09-10 081453](https://github.com/user-attachments/assets/69213592-7bb9-4a9c-b633-d93089dd693e)

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/968-story-change-the-position-of-title-field-in-whole-place-setup
PR: https://github.com/explore-siargao/es-main/pull/1012
