### ISSUE TITLE
[Story] Change Add living room to Add bed in living room on Whole place studio apartment

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#969]
## 🌈 Objective

As a User Host\
I want to be able to easily understand what im going to add in specific field\
So that I'll be able to know what I will going to input in the field

### Requirements
1. Change the label of "Add living room" to "Add beds in living room

### Design Workflow
![Screenshot 2024-09-10 081453](https://github.com/user-attachments/assets/89d7191f-3586-4ebd-a375-fb238412ed23)

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/969-story-change-add-living-room-to-add-bed-in-living-room-on-whole-place-studio-apartment
PR: https://github.com/explore-siargao/es-main/pull/1000
