### ISSUE TITLE
[Story] make Preview button in listing setup dynamic depends if pending or incomplete

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#970]
## 🌈 Objective

As a User Host\
I want to be able to see preview of unpublished listing\
So that I'll be able to review the output of the listing before publishing it.

### Requirements
1. In incomplete status of listing dont show the preview listing button in the header
2. In pending status of listing show the preview listing button in the header

### Design Workflow
Incomplete listing
![Screenshot 2024-09-10 081453](https://github.com/user-attachments/assets/b45380d6-bfc4-4316-8e75-42d6d1586516)

Pending listing
![image](https://github.com/user-attachments/assets/f27a33c9-e503-4eb8-964d-75aee587e8e5)

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/970-story-make-preview-button-in-listing-setup-dynamic-depends-if-pending-or-incomplete
PR: https://github.com/explore-siargao/es-main/pull/990
