### ISSUE TITLE
[FE] Public property page make images more taller

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#971]
## 🌈 Objective

As a Guest\
I want to be able to see property photos more bigger\
So that I'll be able to see clear details of the images of property

### Requirements
1. Adjust the height of image group
2. Add additional height.

### Design Workflow
![Screenshot 2024-09-10 081453](https://github.com/user-attachments/assets/f1f26ff1-db55-427d-956c-b5d07b70835b)

**Comment by Dyayy026** [comment]
PR: https://github.com/explore-siargao/es-main/pull/1080
Branch: https://github.com/explore-siargao/es-main/tree/971-fe-public-property-page-make-images-more-taller
