### ISSUE TITLE
[Story] Mandatory of image descriptions and tags for all image upload

### ISSUE THREAD

**Issue by ramil25** [explore-siargao/es-main#977]
## 🌈 Objective

As a User Host\
I want to be able to required the inputs for image descriptions and tags for image uploads\
So that I'll be able to ensure all uploaded images are properly described and categorized, making them more accessible and improving searchability for users.
### Requirements
1. Make the image description is required for all images.
2. Make the image tags is required for all images.

### Design Workflow
![Screenshot 2024-09-10 081453](https://github.com/user-attachments/assets/e0817c0c-05c6-4546-b64c-609e0eb153b9)

**Comment by Dyayy026** [comment]
Branch: https://github.com/explore-siargao/es-main/tree/977-story-mandatory-of-image-descriptions-and-tags-for-all-image-upload
PR: https://github.com/explore-siargao/es-main/pull/987
